### ISSUE TITLE
definition of field should include all element under addition

### ISSUE THREAD

**Issue by ddl-hust** [KyrinCode/ZKP#1]
https://github.com/KyrinCode/ZKP/blob/main/Field%20and%20Group.md

for this part:
>  Inverse elements: every non-zero element  in the field has an additive inverse  such that , and every non-zero element  in the field has a multiplicative inverse 

**non-zero** element  in the field has an additive inverse -> element  in the field has an additive inverse

**Comment by KyrinCode** [comment]
Yes you are right. I just fixed it. Thx

**Comment by ddl-hust** [comment]
> Yes you are right. I just fixed it. Thx

learned a lot from your note, thanks!
